"""empty message

Revision ID: f71a0d86a361
Revises: 2f873c7ec57e
Create Date: 2019-10-07 23:17:03.796352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f71a0d86a361'
down_revision = '2f873c7ec57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vehicle', sa.Column('fleet_id', sa.Integer(), nullable=True))
    op.drop_constraint('Vehicle_ibfk_1', 'Vehicle', type_='foreignkey')
    op.create_foreign_key(None, 'Vehicle', 'Fleet', ['fleet_id'], ['id'])
    op.drop_column('Vehicle', 'fleet_fk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Vehicle', sa.Column('fleet_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Vehicle', type_='foreignkey')
    op.create_foreign_key('Vehicle_ibfk_1', 'Vehicle', 'Fleet', ['fleet_fk'], ['id'])
    op.drop_column('Vehicle', 'fleet_id')
    # ### end Alembic commands ###
